export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRIES_BY_ID = 'GET_COUNTRIES_BY_ID'
export const GET_COUNTRY_BY_SEARCH = 'GET_COUNTRY_BY_SEARCH'
export const FILTER_CONTINENTS = 'FILTER_CONTINENTS'