export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_COUNTRIES_BY_ID = 'GET_COUNTRIES_BY_ID'
export const GET_COUNTRY_BY_SEARCH = 'GET_COUNTRY_BY_SEARCH'
export const FILTER_CONTINENTS = 'FILTER_CONTINENTS'
export const FILTER_ACTIVITIES = 'FILTER_ACTIVITIES'
export const GET_ACTIVITY = 'GET_ACTIVITY'
export const ORDER_BY_ASCDESC = 'ORDER_BY_ASCDESC'
export const ORDER_BY_POP = 'ORDER_BY_POP'
export const POST_ACTIVITY= 'POST_ACTIVITY'
export const RESET= 'RESET'
export const LOADING = 'LOADING'

